version: "3.7"

services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    ports:
      - "8080:8080"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${GLOBAL_CONFIG_PATH}/qbittorrent:/config
      - ${GLOBAL_DATA_PATH}:/data
    restart: always

  jellyseerr:
    container_name: jellyseerr
    image: ghcr.io/hotio/jellyseerr
    ports:
      - "5055:5055"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${GLOBAL_CONFIG_PATH}/jellyseerr:/config
    restart: always

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    ports:
      - "9696:9696"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${GLOBAL_CONFIG_PATH}/prowlarr:/config
    restart: always

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${GLOBAL_CONFIG_PATH}/radarr:/config
      - ${GLOBAL_DATA_PATH}:/data
    restart: always

  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${GLOBAL_CONFIG_PATH}/sonarr:/config
      - ${GLOBAL_DATA_PATH}:/data
    restart: always

  flaresolver:
    container_name: flaresolver
    image: ghcr.io/flaresolverr/flaresolverr:latest
    ports:
      - "8191:8191"
    environment:
      - LOG_LEVEL=info
    restart: always
    volumes:
      - ${GLOBAL_CONFIG_PATH}/flaresolver:/config

  jellyfin:
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin
    ports:
      - "8096:8096"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${GLOBAL_CONFIG_PATH}/jellyfin:/config
      - ${GLOBAL_DATA_PATH}:/data
    restart: always

  jackett:
    container_name: jackett
    image: ghcr.io/hotio/jackett
    ports:
      - "9117:9117"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${GLOBAL_CONFIG_PATH}/jackett:/config
    restart: always
